version: "3.9"
services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - FRONTEND_URL=http://localhost:3000
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://kbg:kbg@localhost:5432/newsme
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8000
    command: sh -c "npm run build && serve dist" 