"""removed frequency

Revision ID: 8d2ad4e27699
Revises: a7a3855518b3
Create Date: 2025-06-12 16:19:45.731565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d2ad4e27699'
down_revision: Union[str, None] = 'a7a3855518b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'frequency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('frequency', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
